# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emperor/Documents/uni/TransitNetworkModel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emperor/Documents/uni/TransitNetworkModel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emperor/Documents/uni/TransitNetworkModel/CMakeFiles /home/emperor/Documents/uni/TransitNetworkModel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emperor/Documents/uni/TransitNetworkModel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unittest_gtfs

# Build rule for target.
unittest_gtfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest_gtfs
.PHONY : unittest_gtfs

# fast build rule for target.
unittest_gtfs/fast:
	$(MAKE) -f CMakeFiles/unittest_gtfs.dir/build.make CMakeFiles/unittest_gtfs.dir/build
.PHONY : unittest_gtfs/fast

#=============================================================================
# Target rules for targets named transit_network_model

# Build rule for target.
transit_network_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transit_network_model
.PHONY : transit_network_model

# fast build rule for target.
transit_network_model/fast:
	$(MAKE) -f CMakeFiles/transit_network_model.dir/build.make CMakeFiles/transit_network_model.dir/build
.PHONY : transit_network_model/fast

#=============================================================================
# Target rules for targets named load_gtfs

# Build rule for target.
load_gtfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 load_gtfs
.PHONY : load_gtfs

# fast build rule for target.
load_gtfs/fast:
	$(MAKE) -f CMakeFiles/load_gtfs.dir/build.make CMakeFiles/load_gtfs.dir/build
.PHONY : load_gtfs/fast

#=============================================================================
# Target rules for targets named unittest_gps

# Build rule for target.
unittest_gps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest_gps
.PHONY : unittest_gps

# fast build rule for target.
unittest_gps/fast:
	$(MAKE) -f CMakeFiles/unittest_gps.dir/build.make CMakeFiles/unittest_gps.dir/build
.PHONY : unittest_gps/fast

#=============================================================================
# Target rules for targets named unittest_sampling

# Build rule for target.
unittest_sampling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest_sampling
.PHONY : unittest_sampling

# fast build rule for target.
unittest_sampling/fast:
	$(MAKE) -f CMakeFiles/unittest_sampling.dir/build.make CMakeFiles/unittest_sampling.dir/build
.PHONY : unittest_sampling/fast

#=============================================================================
# Target rules for targets named gtfs-realtime

# Build rule for target.
gtfs-realtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtfs-realtime
.PHONY : gtfs-realtime

# fast build rule for target.
gtfs-realtime/fast:
	$(MAKE) -f protobuf/CMakeFiles/gtfs-realtime.dir/build.make protobuf/CMakeFiles/gtfs-realtime.dir/build
.PHONY : gtfs-realtime/fast

#=============================================================================
# Target rules for targets named gps

# Build rule for target.
gps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gps
.PHONY : gps

# fast build rule for target.
gps/fast:
	$(MAKE) -f gps/CMakeFiles/gps.dir/build.make gps/CMakeFiles/gps.dir/build
.PHONY : gps/fast

#=============================================================================
# Target rules for targets named sampling

# Build rule for target.
sampling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sampling
.PHONY : sampling

# fast build rule for target.
sampling/fast:
	$(MAKE) -f sampling/CMakeFiles/sampling.dir/build.make sampling/CMakeFiles/sampling.dir/build
.PHONY : sampling/fast

#=============================================================================
# Target rules for targets named gtfs

# Build rule for target.
gtfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtfs
.PHONY : gtfs

# fast build rule for target.
gtfs/fast:
	$(MAKE) -f gtfs/CMakeFiles/gtfs.dir/build.make gtfs/CMakeFiles/gtfs.dir/build
.PHONY : gtfs/fast

src/load_gtfs.o: src/load_gtfs.cpp.o

.PHONY : src/load_gtfs.o

# target to build an object file
src/load_gtfs.cpp.o:
	$(MAKE) -f CMakeFiles/load_gtfs.dir/build.make CMakeFiles/load_gtfs.dir/src/load_gtfs.cpp.o
.PHONY : src/load_gtfs.cpp.o

src/load_gtfs.i: src/load_gtfs.cpp.i

.PHONY : src/load_gtfs.i

# target to preprocess a source file
src/load_gtfs.cpp.i:
	$(MAKE) -f CMakeFiles/load_gtfs.dir/build.make CMakeFiles/load_gtfs.dir/src/load_gtfs.cpp.i
.PHONY : src/load_gtfs.cpp.i

src/load_gtfs.s: src/load_gtfs.cpp.s

.PHONY : src/load_gtfs.s

# target to generate assembly for a file
src/load_gtfs.cpp.s:
	$(MAKE) -f CMakeFiles/load_gtfs.dir/build.make CMakeFiles/load_gtfs.dir/src/load_gtfs.cpp.s
.PHONY : src/load_gtfs.cpp.s

src/transit_network_model.o: src/transit_network_model.cpp.o

.PHONY : src/transit_network_model.o

# target to build an object file
src/transit_network_model.cpp.o:
	$(MAKE) -f CMakeFiles/transit_network_model.dir/build.make CMakeFiles/transit_network_model.dir/src/transit_network_model.cpp.o
.PHONY : src/transit_network_model.cpp.o

src/transit_network_model.i: src/transit_network_model.cpp.i

.PHONY : src/transit_network_model.i

# target to preprocess a source file
src/transit_network_model.cpp.i:
	$(MAKE) -f CMakeFiles/transit_network_model.dir/build.make CMakeFiles/transit_network_model.dir/src/transit_network_model.cpp.i
.PHONY : src/transit_network_model.cpp.i

src/transit_network_model.s: src/transit_network_model.cpp.s

.PHONY : src/transit_network_model.s

# target to generate assembly for a file
src/transit_network_model.cpp.s:
	$(MAKE) -f CMakeFiles/transit_network_model.dir/build.make CMakeFiles/transit_network_model.dir/src/transit_network_model.cpp.s
.PHONY : src/transit_network_model.cpp.s

test_gps.o: test_gps.cpp.o

.PHONY : test_gps.o

# target to build an object file
test_gps.cpp.o:
	$(MAKE) -f CMakeFiles/unittest_gps.dir/build.make CMakeFiles/unittest_gps.dir/test_gps.cpp.o
.PHONY : test_gps.cpp.o

test_gps.i: test_gps.cpp.i

.PHONY : test_gps.i

# target to preprocess a source file
test_gps.cpp.i:
	$(MAKE) -f CMakeFiles/unittest_gps.dir/build.make CMakeFiles/unittest_gps.dir/test_gps.cpp.i
.PHONY : test_gps.cpp.i

test_gps.s: test_gps.cpp.s

.PHONY : test_gps.s

# target to generate assembly for a file
test_gps.cpp.s:
	$(MAKE) -f CMakeFiles/unittest_gps.dir/build.make CMakeFiles/unittest_gps.dir/test_gps.cpp.s
.PHONY : test_gps.cpp.s

test_gtfs.o: test_gtfs.cpp.o

.PHONY : test_gtfs.o

# target to build an object file
test_gtfs.cpp.o:
	$(MAKE) -f CMakeFiles/unittest_gtfs.dir/build.make CMakeFiles/unittest_gtfs.dir/test_gtfs.cpp.o
.PHONY : test_gtfs.cpp.o

test_gtfs.i: test_gtfs.cpp.i

.PHONY : test_gtfs.i

# target to preprocess a source file
test_gtfs.cpp.i:
	$(MAKE) -f CMakeFiles/unittest_gtfs.dir/build.make CMakeFiles/unittest_gtfs.dir/test_gtfs.cpp.i
.PHONY : test_gtfs.cpp.i

test_gtfs.s: test_gtfs.cpp.s

.PHONY : test_gtfs.s

# target to generate assembly for a file
test_gtfs.cpp.s:
	$(MAKE) -f CMakeFiles/unittest_gtfs.dir/build.make CMakeFiles/unittest_gtfs.dir/test_gtfs.cpp.s
.PHONY : test_gtfs.cpp.s

test_sampling.o: test_sampling.cpp.o

.PHONY : test_sampling.o

# target to build an object file
test_sampling.cpp.o:
	$(MAKE) -f CMakeFiles/unittest_sampling.dir/build.make CMakeFiles/unittest_sampling.dir/test_sampling.cpp.o
.PHONY : test_sampling.cpp.o

test_sampling.i: test_sampling.cpp.i

.PHONY : test_sampling.i

# target to preprocess a source file
test_sampling.cpp.i:
	$(MAKE) -f CMakeFiles/unittest_sampling.dir/build.make CMakeFiles/unittest_sampling.dir/test_sampling.cpp.i
.PHONY : test_sampling.cpp.i

test_sampling.s: test_sampling.cpp.s

.PHONY : test_sampling.s

# target to generate assembly for a file
test_sampling.cpp.s:
	$(MAKE) -f CMakeFiles/unittest_sampling.dir/build.make CMakeFiles/unittest_sampling.dir/test_sampling.cpp.s
.PHONY : test_sampling.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... unittest_gtfs"
	@echo "... transit_network_model"
	@echo "... load_gtfs"
	@echo "... unittest_gps"
	@echo "... unittest_sampling"
	@echo "... gtfs-realtime"
	@echo "... gps"
	@echo "... sampling"
	@echo "... gtfs"
	@echo "... src/load_gtfs.o"
	@echo "... src/load_gtfs.i"
	@echo "... src/load_gtfs.s"
	@echo "... src/transit_network_model.o"
	@echo "... src/transit_network_model.i"
	@echo "... src/transit_network_model.s"
	@echo "... test_gps.o"
	@echo "... test_gps.i"
	@echo "... test_gps.s"
	@echo "... test_gtfs.o"
	@echo "... test_gtfs.i"
	@echo "... test_gtfs.s"
	@echo "... test_sampling.o"
	@echo "... test_sampling.i"
	@echo "... test_sampling.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

